Use C99 stdbool.h instead of a custom typedef
On Darwin and other platforms a plain signed int and then creating
a conflict:

../include/captagent/api.h:120:22: error: cannot combine with previous 'int' declaration specifier
typedef unsigned int bool;